### DISCUSSION TITLE
Question regarding close_on_passing & close_on_passing_min_wait (auto-close behavior)

### DISCUSSION THREAD

**Discussion by yada** [cncf/gitvote#615] [Q&A] [answered]
Hi,

I'm reaching out with a question about our current gitvote configuration. I’m trying to understand why the `close_on_passing` and `close_on_passing_min_wait` settings don’t seem to work as expected.

We intend to have issues and PRs automatically closed only after 1 week, even if the vote passes quickly, this is to leave time for community feedback. Here’s the configuration we’re using:
```
profiles:
  default:
    # Enforce policies described in our governance file, see: https://github.com/microcks/.github/blob/main/GOVERNANCE.md
    duration: 2w
    pass_threshold: 66
    # Check vote status every day, default is fine for us here
    periodic_status_check: "1 day"
    # Let automate the issue or PR closing when the vote is done 👍
    close_on_passing: true
    # This allows participants sufficient opportunity to engage
    # and reflect before the vote is automatically finalized; 1 week for community feedback and comments
    close_on_passing_min_wait: "1 week"
    # Currently and according to our governance file, only maintainers have the right to vote
    # You are still encouraged to participate in voting, even if your vote is not binding, ref: close_on_passing_min_wait option above
    allowed_voters:
      users:
        - lbroudoux
        - yada
      exclude_team_maintainers: false

    # TODO: It will be nice to see if we can announce votes on Discord or https://github.com/orgs/microcks/discussions/categories/announcements
    # Using the announcements, ref: https://github.com/cncf/gitvote/blob/main/docs/config/.gitvote.yml 
```

However, issues are not closing automatically. For example:
https://github.com/microcks/community/issues/60
https://github.com/microcks/community/issues/61

Could this be a bug, or am I missing something in the setup?
Thanks in advance for your help.

Best regards,
Yacine
