### ISSUE TITLE
what are all the rules for closing the vote

### ISSUE THREAD

**Issue by derberg** [cncf/gitvote#553]
Since there is no command for manually closing the vote, I need a clarification

This is our config:
```yaml
profiles:
  default:
    duration: 4w
    pass_threshold: 51
    periodic_status_check: "1 week"
    close_on_passing: false
```

I do not want to set `close_on_passing: true` because we have a rule that people should have at least 7 days to vote. Even if `pass_threshold` is met, their opinion still matters.

Can you explain me then how will it work. Does it mean, with the current config, that even if `pass_threshold` is met, the vote will be open `4w` anyway.

How to set it properly, so:
- max we wait for peope 4 weeks
- min we wait for people 7 days
- after 7 days, if `pass_threshold` is met, the vote is closed

Any way to have some command to close voting earlier, manually, if the threshold is met?

Thanks in advance!
